swagger: '2.0'
info:
  title: Refresh Token
  description: Endpoint para renovar o access token do usuário autenticado.
  version: "1.0"

tags:
  - Auth

summary: Gera um novo access token
description: >
  Recebe um refresh token válido enviado via cookies HttpOnly e retorna um novo access token.
  O refresh token deve estar ativo e não expirado.

security:
  - BearerAuth: []

produces:
  - application/json

responses:
  200:
    description: Novo access token emitido com sucesso
    schema:
      type: object
      properties:
        access_token:
          type: string
          example: eyJhbGciOiJIUzI1...

  401:
    description: Refresh token inválido ou expirado
